const GET_USERS_SAGA = "GET_USERS_SAGA";
const SET_USERS = "SET_USERS";
const LOGIN_SAGA = "LOGIN_SAGA";
const SET_TOKEN = "SET_TOKEN";

export {
  GET_USERS_SAGA,
  SET_USERS,
  LOGIN_SAGA,
  SET_TOKEN
};
