export const conditionData = [
    { numerical: 10.0, abbreviation: 'GM', name: 'Gem Mint', code: 'GEM_MINT' },
    { numerical: 9.9, abbreviation: 'MT', name: 'Mint', code: 'MINT' },
    { numerical: 9.8, abbreviation: 'NM/MT', name: 'Near Mint/Mint', code: 'NEAR_MINT_MINT' },
    { numerical: 9.6, abbreviation: 'NM+', name: 'Near Mint+', code: 'NEAR_MINT_PLUS' },
    { numerical: 9.4, abbreviation: 'NM', name: 'Near Mint', code: 'NEAR_MINT' },
    { numerical: 9.2, abbreviation: 'NM-', name: 'Near Mint-', code: 'NEAR_MINT_MINUS' },
    { numerical: 9.0, abbreviation: 'VF/NM', name: 'Very Fine/Near Mint', code: 'VERY_FINE_NEAR_MINT' },
    { numerical: 8.5, abbreviation: 'VF+', name: 'Very Fine+', code: 'VERY_FINE_PLUS' },
    { numerical: 8.0, abbreviation: 'VF', name: 'Very Fine', code: 'VERY_FINE' },
    { numerical: 7.5, abbreviation: 'VF-', name: 'Very Fine-', code: 'VERY_FINE_MINUS' },
    { numerical: 7.0, abbreviation: 'FN/VF', name: 'Fine/Very Fine', code: 'FINE_VERY_FINE' },
    { numerical: 6.5, abbreviation: 'FN+', name: 'Fine+', code: 'FINE_PLUS' },
    { numerical: 6.0, abbreviation: 'FN', name: 'Fine', code: 'FINE' },
    { numerical: 5.5, abbreviation: 'FN-', name: 'Fine-', code: 'FINE_MINUS' },
    { numerical: 5.0, abbreviation: 'VG/FN', name: 'Very Good/Fine', code: 'VERY_GOOD_FINE' },
    { numerical: 4.5, abbreviation: 'VG+', name: 'Very Good+', code: 'VERY_GOOD_PLUS' },
    { numerical: 4.0, abbreviation: 'VG', name: 'Very Good', code: 'VERY_GOOD' },
    { numerical: 3.5, abbreviation: 'VG-', name: 'Very Good-', code: 'VERY_GOOD_MINUS' },
    { numerical: 3.0, abbreviation: 'GD/VG', name: 'Good/Very Good', code: 'GOOD_VERY_GOOD' },
    { numerical: 2.5, abbreviation: 'GD+', name: 'Good+', code: 'GOOD_PLUS' },
    { numerical: 2.0, abbreviation: 'GD', name: 'Good', code: 'GOOD' },
    { numerical: 1.8, abbreviation: 'GD-', name: 'Good-', code: 'GOOD_MINUS' },
    { numerical: 1.5, abbreviation: 'FR/GD', name: 'Fair/Good', code: 'FAIR_GOOD' },
    { numerical: 1.0, abbreviation: 'FR', name: 'Fair', code: 'FAIR' },
    { numerical: 0.5, abbreviation: 'PR', name: 'Poor', code: 'POOR' },
    { numerical: 0.3, abbreviation: 'INC', name: 'Incomplete', code: 'INCOMPLETE_3' },
    { numerical: 0.1, abbreviation: 'INC', name: 'Incomplete', code: 'INCOMPLETE_1' },
  ];
  