version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      target: build-deps
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_SERVER_PORT}:${CLIENT_SERVER_PORT}
    environment:
      PORT: ${CLIENT_SERVER_PORT}
    command: yarn start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./api
      target: development
    environment:
      DB_HOST: database
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    # command: npm run start:debugdocker
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: