const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const LOGIN_SAGA = 'LOGIN_SAGA';
const SET_TOKEN = 'SET_TOKEN';

const SET_ACTIVE_SERIES = 'SET_ACTIVE_SERIES';
const SET_ACTIVE_ISSUE = 'SET_ACTIVE_ISSUE';

const SET_BIN = 'SET_BIN';
const SET_TAG = 'SET_TAG';
const SET_NOTES = 'SET_NOTES';
const SET_COST = 'SET_COST';
const SET_AQUIRED = 'SET_AQUIRED';

const SET_ACTIVE_CONDITION = 'SET_ACTIVE_CONDITION';
const SET_ACTIVE_GRADER = 'SET_ACTIVE_GRADER';
const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
const SET_ACTIVE_VENDOR = 'SET_ACTIVE_VENDOR';

const CREATE_INVENTORY_SAGA = 'CREATE_INVENTORY_SAGA';
const GET_INVENTORY_SAGA = 'GET_INVENTORY_SAGA';
const SET_INVENTORY = 'SET_INVENTORY';

const GET_PENDING_APPROVALS_SAGA = 'GET_PENDING_APPROVALS_SAGA';
const SET_PENDING_APPROVALS = 'SET_PENDING_APPROVALS';

export {
  GET_USERS_SAGA,
  SET_USERS,
  LOGIN_SAGA,
  SET_TOKEN,
  SET_ACTIVE_SERIES,
  SET_ACTIVE_ISSUE,
  SET_BIN,
  SET_TAG,
  SET_NOTES,
  SET_COST,
  SET_ACTIVE_PAGE,
  SET_ACTIVE_VENDOR,
  SET_AQUIRED,
  SET_ACTIVE_CONDITION,
  SET_ACTIVE_GRADER,
  CREATE_INVENTORY_SAGA,
  GET_INVENTORY_SAGA,
  SET_INVENTORY,
  GET_PENDING_APPROVALS_SAGA,
  SET_PENDING_APPROVALS,
};
