const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const LOGIN_SAGA = 'LOGIN_SAGA';
const SET_TOKEN = 'SET_TOKEN';

const GET_CONDITIONS_SAGA = 'GET_CONDITIONS_SAGA';
const SET_CONDITIONS = 'SET_CONDITIONS';
const SET_ACTIVE_CONDITION = 'SET_ACTIVE_CONDITION';

const GET_GRADERS_SAGA = 'GET_GRADERS_SAGA';
const SET_GRADERS = 'SET_GRADERS';
const SET_ACTIVE_GRADER = 'SET_ACTIVE_GRADER';

const SET_ACTIVE_SERIES = 'SET_ACTIVE_SERIES';
const SET_ACTIVE_ISSUE = 'SET_ACTIVE_ISSUE';
const SET_BIN = 'SET_BIN';
const SET_TAG = 'SET_TAG';
const SET_NOTES = 'SET_NOTES';
const SET_COST = 'SET_COST';
const SET_AQUIRED = 'SET_AQUIRED';
const ADD_INVENTORY = 'ADD_INVENTORY';
const GET_INVENTORY = 'GET_INVENTORY';
const SET_PAGE = 'SET_PAGE';
const SET_VENDOR = 'SET_VENDOR';

export {
  GET_USERS_SAGA,
  SET_USERS,
  LOGIN_SAGA,
  SET_TOKEN,

  GET_CONDITIONS_SAGA,
  SET_CONDITIONS,
  SET_ACTIVE_CONDITION,

  GET_GRADERS_SAGA,
  SET_GRADERS,
  SET_ACTIVE_GRADER,

  SET_ACTIVE_SERIES,
  SET_ACTIVE_ISSUE,
  SET_BIN,
  SET_TAG,
  SET_NOTES,
  SET_COST,
  SET_GRADER,
  SET_PAGE,
  SET_VENDOR,
  SET_AQUIRED,
  ADD_INVENTORY,
  GET_INVENTORY,
};
